map:
  resolution: 0.1
  map_x_l: -20.0
  map_x_u: 20.0
  map_y_l: -20.0
  map_y_u: 20.0

planning: 
  start_x: 4.0
  start_y: 0.0
  start_z: -0.7     # Project to ground level (laser_link - 0.7m = base_link)
  target_x: 10.0
  target_y: 5.0
  target_z: -0.7    # Target also at ground level

  step_size: 0.3
  h_surf_car: 0.3   # Car base height above ground (~0.3m)

  radius_fit_plane: 1.0  # Larger radius for better ground fitting

  w_flatness: 2000.0
  w_slope: 0.03
  w_sparsity: 0.2
  w_fit_plane: 0.5
  ratio_max: 0.1
  ratio_min: 0.02
  conv_thre: 0.1152


